apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-utils.serviceAccountName" . }}
  labels:
    {{- include "ingress-utils.labels" . | nindent 4 }}
{{- if semverCompare ">=1.24.0-0" .Capabilities.KubeVersion.GitVersion }}
secrets:
  - name: {{ include "ingress-utils.serviceAccountTokenName" . }}
{{- end }}

{{- if semverCompare ">=1.24.0-0" .Capabilities.KubeVersion.GitVersion }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingress-utils.serviceAccountTokenName" . }}
  labels:
    {{- include "ingress-utils.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "ingress-utils.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-utils.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "ingress-utils.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
