kind: ClusterRole
rules:
  - apiGroups:
      - 'extensions.kubesphere.io'
      - 'iam.kubesphere.io'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ''
      - 'apps'
      - 'rbac.authorization.k8s.io'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - 'apiextensions.k8s.io'
      - 'apiregistration.k8s.io'
      - 'admissionregistration.k8s.io'
    resources:
      - '*'
    verbs:
      - '*'

---
kind: Role
rules:
  - apiGroups:
      - 'networking.k8s.io'
      - 'extensions'
    resources:
      - 'ingresses'
    verbs:
      - '*'